[package]
name = "koatl"
version = "0.3.15"
edition = "2021"
homepage = "https://koatl.org"

[lib]
name = "koatl"
crate-type = ["cdylib"]

[dependencies]
koatl-core = { path = "../koatl-core" }
pyo3 = "0.25.0"
ariadne = "0.5.1"
once_cell = "1.19.0"